django-crispy-forms/django-crispy-forms

- .travis.yml
As per comment from @kevin-brown on #450
> Don't use sudo for Travis

- crispy_forms/base.py
> Remove crispy_forms.base.from_iterable. #462

- crispy_forms/tests/test_layout_objects.py
About the same like #470, but I leaved some classes, just to not mark all tests separately. Probably further there will be some restructuring.
> Convert test_layout.py module

- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_settings.py
Also move TEMPLATE_DIRS and TEMPLATE_LOADERS settings to test_settings module.
> Convert test_layout module to py.test style.

- crispy_forms/compatibility.py
- crispy_forms/layout.py
- crispy_forms/templatetags/crispy_forms_field.py
- crispy_forms/templatetags/crispy_forms_filters.py
- crispy_forms/templatetags/crispy_forms_tags.py
- crispy_forms/templatetags/crispy_forms_utils.py
- crispy_forms/utils.py
#472 
To solve the problem with minimal code changes I've replaced TEMPLATE_PACK variable with lazy object from django.
> Replace global variable with lazy object

- crispy_forms/tests/test_settings.py
> Remove redundant global_settings usage

- crispy_forms/templatetags/crispy_forms_utils.py
Both condition branches execute the same code. So, condition is useless.
> Simplify function selectively_remove_spaces_between_tags

- crispy_forms/templates/bootstrap3/layout/prepended_appended_text.html
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_settings.py
- crispy_forms/tests/test_tags.py
- crispy_forms/tests/urls.py
Unfortunately some tests became broken, and I don't know yet how to fix it. Please, take a look at failures, I believe, that it can be fixed easily.
Thanks!
> Fixes based on coverage report

- README.rst
Switch codecov badge from master to dev branch (correct version of #487)
> Fix Codecov badge in README

- crispy_forms/compatibility.py
- crispy_forms/templatetags/crispy_forms_filters.py
- crispy_forms/templatetags/crispy_forms_tags.py
- crispy_forms/utils.py
Closes #430
Cherry picked some commits from @davidfischer-ch. I didn't include some original commits. If you want, a can add it.
> Favour lru-cache over memoize

- docs/crispy_tag_forms.rst
django-jsonview needs a '_' to be used as a tag
> fix the tag on example 'AJAX validation recipe'

- docs/crispy_tag_forms.rst
> Update the AJAX validation docs wih code that works for recent Django

- .travis.yml
- crispy_forms/bootstrap.py
- crispy_forms/compatibility.py
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
- crispy_forms/tests/test_settings.py
- crispy_forms/tests/urls.py
- tox.ini
Fix labels for checkboxes and radiobuttons, and fix `form-control-lg` and `form-control-sm` for PrependedAppendedText widgets.
Closes https://github.com/maraujop/django-crispy-forms/issues/531
Before:
After:
> Minor Bootstrap 4 improvements

- docs/install.rst
> Improve documentation for CRISPY_TEMPLATE_PACK

- .gitignore
- crispy_forms/bootstrap.py
- crispy_forms/layout.py
My env is being funky, so I'm just going to use the PR to see if the
tests pass...
> 1.9 warnings round 2: render_to_string.

- .travis.yml
- crispy_forms/tests/test_form_helper.py
- tox.ini
Fixed a test by removing a hack since it was for a since fixed
regression.
Closes https://github.com/maraujop/django-crispy-forms/issues/558
> Add explicit Django 1.9 testing and working tests

- crispy_forms/templates/bootstrap/table_inline_formset.html
- crispy_forms/templates/bootstrap3/table_inline_formset.html
- crispy_forms/templates/bootstrap4/table_inline_formset.html
This patch fixes https://github.com/maraujop/django-crispy-forms/issues/544
> Fix for Issue #544

- crispy_forms/helper.py
- crispy_forms/templates/bootstrap4/field.html
- crispy_forms/templates/bootstrap4/inputs.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple_inline.html
- crispy_forms/templates/bootstrap4/layout/field_with_buttons.html
- crispy_forms/templates/bootstrap4/layout/formactions.html
- crispy_forms/templates/bootstrap4/layout/inline_field.html
- crispy_forms/templates/bootstrap4/layout/prepended_appended_text.html
- crispy_forms/templates/bootstrap4/layout/radioselect_inline.html
- crispy_forms/templates/bootstrap4/layout/uneditable_input.html
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
Closes https://github.com/maraujop/django-crispy-forms/issues/573
Hey @carltongibson, can you take a look at this and let me know what you think of this solution?
> Fix "vertical" bootstrap 4 form with flexbox enabled

- CONTRIBUTORS.txt
Hey - Thanks for accepting #579.  I forgot to add myself to the contributors list, so this is a small follow-up PR to do it.  No tests this time, sorry. ;-)
> Add to contributors for PR #579

- crispy_forms/templates/bootstrap4/layout/help_text.html
- crispy_forms/tests/test_form_helper.py
bootstrap changed helptext styling
> bootstrap 4 help text smaller

- CHANGELOG.md
> Document in Changelog that Django 1.7 support has been dropped

- crispy_forms/templates/bootstrap3/layout/inline_field.html
- crispy_forms/templates/bootstrap4/layout/inline_field.html
Add wrapper_class to bootstrap 3 and 4 InlineFields template #640
> Add wrapper_class to bootstrap InlineFields

- crispy_forms/helper.py
So I keep this out of my other PR
> Fix typo in docstring

- crispy_forms/tests/test_form_helper.py
#642 failed to update the tests in line with the changes. This does that.
> Update tests in line with #642

- crispy_forms/layout.py
> 1 line pass unused kwarg

- crispy_forms/templates/bootstrap3/layout/prepended_appended_text.html
Add support for wrapper_class on Prepend / Append fields
> Support wrapper_class

- crispy_forms/templates/bootstrap/table_inline_formset.html
- crispy_forms/templates/bootstrap3/table_inline_formset.html
- crispy_forms/templates/bootstrap4/table_inline_formset.html
Added empty_form so people can use javascript to add more rows if they need to.
> added empty_form to formsets made with table_inline_formset.html

- crispy_forms/templatetags/crispy_forms_filters.py
Closes #547 — just updates to current `dev`
> Add label_class and field_class to as_crispy_field

- crispy_forms/templatetags/crispy_forms_field.py
- crispy_forms/tests/forms.py
- crispy_forms/tests/test_form_helper.py
Replaces #561 
Closes #560 
Given age of original PR, happy to merge as is.
> Don't add 'form-control' class to multi value fields

- crispy_forms/templatetags/crispy_forms_filters.py
> Use helper of field form in `as_crispy_field` filter

- crispy_forms/templates/bootstrap/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap/layout/radioselect.html
- crispy_forms/templates/bootstrap3/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap3/layout/radioselect.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
- crispy_forms/tests/forms.py
- crispy_forms/tests/test_layout.py
This fixes #701. A test is included.
> Convert field value from None to '' in choice fields, instead of 'None'

- crispy_forms/tests/forms.py
- crispy_forms/tests/test_layout_objects.py
See commit message for further details
> [tests] SplitDateTimeWidget must be used with SplitDateTimeField rather than DateTimeField

- crispy_forms/templates/bootstrap4/layout/field_errors.html
- crispy_forms/templates/bootstrap4/layout/field_errors_block.html
- crispy_forms/templatetags/crispy_forms_field.py
- crispy_forms/tests/test_form_helper.py
> Fix Bootstrap 4 field error classes

- crispy_forms/templates/bootstrap/field.html
- crispy_forms/templates/bootstrap3/field.html
- crispy_forms/templates/bootstrap4/field.html
Closes https://github.com/django-crispy-forms/django-crispy-forms/issues/705
> Show required asterisk on required checkboxes

- crispy_forms/layout.py
> Add wrapper_class to MultiWidgetField

- crispy_forms/templates/bootstrap/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap/layout/radioselect.html
- crispy_forms/templates/bootstrap3/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap3/layout/radioselect.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
All other elements honor this correctly, but radio and multi checkboxes
do not.
> Honor element ID set in Django for radio and multi checkboxes

- crispy_forms/layout_slice.py
- crispy_forms/tests/test_layout.py
Like they're special in Div and Field constructors
Fixes https://github.com/django-crispy-forms/django-crispy-forms/issues/754
> CSS classes are special in update_attributes

- .travis.yml
- CHANGELOG.md
- crispy_forms/__init__.py
- crispy_forms/helper.py
- crispy_forms/layout_slice.py
- crispy_forms/templates/bootstrap/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap/layout/radioselect.html
- crispy_forms/templates/bootstrap3/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap3/layout/radioselect.html
- crispy_forms/templates/bootstrap4/field.html
- crispy_forms/templates/bootstrap4/inputs.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple_inline.html
- crispy_forms/templates/bootstrap4/layout/field_with_buttons.html
- crispy_forms/templates/bootstrap4/layout/formactions.html
- crispy_forms/templates/bootstrap4/layout/help_text.html
- crispy_forms/templates/bootstrap4/layout/inline_field.html
- crispy_forms/templates/bootstrap4/layout/prepended_appended_text.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
- crispy_forms/templates/bootstrap4/layout/radioselect_inline.html
- crispy_forms/templates/bootstrap4/layout/tab-link.html
- crispy_forms/templates/bootstrap4/layout/uneditable_input.html
- crispy_forms/templates/bootstrap4/table_inline_formset.html
- crispy_forms/templatetags/crispy_forms_field.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
- crispy_forms/tests/test_tags.py
- docs/form_helper.rst
- tox.ini
Adds Bootstrap 4 compat, plus a few minor fixes.
> Version 1.7.1 Release

- crispy_forms/templates/bootstrap4/field.html
> Remove Error Class from Field Wrapper

- crispy_forms/templates/bootstrap/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap3/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/tests/test_layout_objects.py
> Fix Ambiguous IDs in checkboxes inputs

- crispy_forms/templates/bootstrap/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap3/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/field.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/field_with_buttons.html
- crispy_forms/tests/test_layout_objects.py
- docs/install.rst
> Version 1.7.2

- .travis.yml
- requirements.txt
- tox.ini
Rather than defining the matrix in two places.
> Updated Travis config to use tox

- crispy_forms/templates/bootstrap3/layout/prepended_appended_text.html
- crispy_forms/templates/bootstrap4/layout/prepended_appended_text.html
I'll create a pull request for crispy-test-project that allows easily testing this patch.
> Fixes #819: bootstrap 4 (and 3) select field with appended or prepended text not working properly

- docs/form_helper.rst
Fixed a typo, and a few small grammatical and idiomatic changes to improve clarity.
> Small edits for grammar and clarity

- crispy_forms/templates/bootstrap/uni_form.html
- crispy_forms/templates/bootstrap3/uni_form.html
- crispy_forms/templates/bootstrap4/uni_form.html
- crispy_forms/templates/uni_form/uni_form.html
- crispy_forms/tests/test_form_helper.py
> Allow field_template to be changed with template packs

- crispy_forms/templates/bootstrap4/layout/tab.html
- setup.cfg
> update tabholder template for bootstrap4

- crispy_forms/templates/bootstrap3/table_inline_formset.html
- crispy_forms/templates/bootstrap4/table_inline_formset.html
Is there a reason to hide Labels related to checkboxes ?
> "Delete" label should be rendered as well

- README.rst
Update supported python/django versions to match the tox test matrix
> Update README to reflect the tox test matrix

- crispy_forms/tests/test_tags.py
- docs/template_packs.rst
A couple of small typo's in the comments / docs.
> Correct typos

- crispy_forms/templates/bootstrap4/errors.html
- crispy_forms/templates/bootstrap4/errors_formset.html
> Fix margin on error list

- crispy_forms/helper.py
- crispy_forms/tests/test_form_helper.py
This includes #877 for working tests. If #877 is merged before this one, the diff will be nicer, but I can also isolate the relevant changes if that is preferred.
> Bs4 offset checkboxes

- docs/concepts.rst
- docs/contributing.rst
* Updated links to current repository
* Updated django-uni-form
EDIT : p.s. I think I've got all the name changes now 🤞
> Documentation | fix links and names to current repository

- crispy_forms/tests/test_tags.py
> Fix simple typo: tring -> trying

- crispy_forms/templatetags/crispy_forms_filters.py
- crispy_forms/templatetags/crispy_forms_utils.py
- crispy_forms/tests/forms.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
As we start to look at running flake8 against the project using GitHub actions a number of changes will be needed to fix all of the errors. 
This PR is resolves blank line errors.
> fix flake8 blank lines

- crispy_forms/tests/forms.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout_objects.py
Fixes whitespace errors highlighted by flake8.
> fix flake8 whitespace (E2)

- crispy_forms/tests/test_form_helper.py
The tests are highlighting a small number of deprecated features in Django 4.0
This PR makes the required changes
Side benefit of **significantly** shorter job logs on Travis CI 👍
> Django 4.0 deprecations

- crispy_forms/tests/forms.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
Fixes indentation formatting issues highlighted by flake8
> Flake8 indentation (E1)

- crispy_forms/bootstrap.py
- crispy_forms/compatibility.py
- crispy_forms/tests/test_layout_objects.py
- crispy_forms/utils.py
A few more small changes as highlighted by flake8.
> flake8 refactoring

- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
I missed a couple of these changes in a previous pull request to fix all the deprecation warning for Django4.
Also got a new device and setting up workflow again, I didn't intend to create a new branch here (sorry).
> ugettext to gettext

- docs/form_helper.rst
A typo fixed
automagically -> automatically
> A type fixed

- .pre-commit-config.yaml
- docs/contributing.rst
- pyproject.toml
- requirements.txt
Added hooks for Black, isort and Flake8
Updated Black settings to only apply to crispy_forms folder
Added notes to docs on how to setup pre-commit
> Add pre-commit hooks

- setup.py
Implementing the change suggested in #1014 
Closes #1014
> Add required version of python

- docs/crispy_tag_forms.rst
Note: Django 1.8 was released in April 2015.
> Remove old Django 1.8 note

- crispy_forms/templates/bootstrap4/layout/field_file.html
> Avoids possible XSS when attaching files.

- crispy_forms/templates/bootstrap4/layout/field_file.html
- crispy_forms/tests/test_layout.py
> Disabled File Field

- crispy_forms/templates/bootstrap4/layout/field_file.html
@bryan-brancotte @cpina 
Appreciate thoughts. 
Thanks both. 
Fixes #1043 
**Before**
**After**
> Fixed alignment of checkbox in filefield

- crispy_forms/tests/conftest.py
- crispy_forms/tests/forms.py
- crispy_forms/tests/test_dynamic_api.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
- crispy_forms/utils.py
The magic comma is now more important for `black`. I've manually adjusted a few, others are debatable. I'll leave it here for a bit in case anyone has any comments / strong preferences.
> Updated black

- crispy_forms/tests/test_tags.py
This commit changed the messages when too many forms are submitted in a formset.
https://github.com/django/django/commit/848770dd2c5dec6c805d67f470eb936f38b9421d
> Fixed Formset test for Django 3.2

- .pre-commit-config.yaml
> Updated pre-commit versions

- crispy_forms/tests/forms.py
@kuttamuwa -- I think this should fix your issue?
> Fixed #802 -- Added Max Length to models.CharField

- crispy_forms/helper.py
First PR from the new pi400 :smile: 
Not yet worked out how to run the tests via the VSCode test runner (Pytest works in the command line just fine...)
> Changed url() to path() in doc string

- docs/concepts.rst
- docs/contributing.rst
- docs/crispy_tag_forms.rst
- docs/faq.rst
- docs/filters.rst
- docs/form_helper.rst
- docs/index.rst
- docs/install.rst
- docs/layouts.rst
Nothing major: acronyms in capitals, use of https, update names, etc.
> Documentation consistency

- LICENSE.txt
- docs/conf.py
> Update copyright notices

- .github/workflows/ci-testing-django-master.yml
- .github/workflows/ci-testing.yml
- .github/workflows/publish.yml
- CHANGELOG.md
Hi All
We've got a couple of nice changes on the main branch so I think it's time for the next release.
I'd like to also try and 'automate' the release somewhat. Can I ask for a review of the GHA here @carltongibson @cpina?
> Release 1.11

- .github/workflows/publish.yml
Grumble... how do I test github actions without testing it in "live" grumble....
> Added `runs-on` to Publish Action

- CHANGELOG.md
Happy 2021!
Noticed small typo when reading the change log.
> Fix change log year for 1.11.0

- README.rst
- docs/install.rst
> Doc'd references to bootstrap5 template pack

- crispy_forms/layout.py
- crispy_forms/templates/bootstrap3/layout/baseinput.html
- crispy_forms/templates/bootstrap4/layout/baseinput.html
- crispy_forms/templates/uni_form/layout/baseinput.html
Test coverage in `crispy_forms/tests/test_form_helper.py::test_inputs`
https://github.com/django-crispy-forms/django-crispy-forms/blob/6ba5a42144fbeede54d20eefeb26bc820995decf/crispy_forms/tests/test_form_helper.py#L25
https://github.com/django-crispy-forms/django-crispy-forms/blob/6ba5a42144fbeede54d20eefeb26bc820995decf/crispy_forms/tests/test_form_helper.py#L42
> Moved BaseInput `id` generation to `__init__` method.

- crispy_forms/templates/bootstrap4/layout/uneditable_input.html
- crispy_forms/tests/results/bootstrap4/test_layout/test_uneditable_field.html
- crispy_forms/tests/results/bootstrap4/test_layout/test_use_custom_control_in_uneditable_select_false.html
- crispy_forms/tests/results/bootstrap4/test_layout/test_use_custom_control_in_uneditable_select_true.html
- crispy_forms/tests/test_layout.py
This PR resolves issue #1223 by restoring the layout of UneditableFields, as it was before 65897114358ab9d8b0da3f5d0b791d2ce77e63d0 and adds tests for it.
> Fix UneditableFields

- .pre-commit-config.yaml
- crispy_forms/bootstrap.py
- crispy_forms/layout.py
- requirements/lint.txt
> Added flake8-comprehensions.

- .github/workflows/main.yml
- .github/workflows/publish.yml
Update GitHub action workflow versions.
(I thought depndabot would open PRs to update this 🤷 )
> Update GitHub action versions in workflows.
