django-crispy-forms/django-crispy-forms

- requirements.txt
- setup.py
Fixes #459
* Make sure we've got wheel installed. 
* Wrap upload in `publish` command a la @tomchristie's template.
> Add wheel and twine dependencies for PyPI uploads

- crispy_forms/tests/base.py
- crispy_forms/tests/conftest.py
- crispy_forms/tests/runtests.py
- crispy_forms/tests/test_dynamic_api.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
- crispy_forms/tests/test_tags.py
Fixes #465 
Here we have globally set CRISPY_TEMPLATE_PACK settings in each run. Before we have to select some tests for each template pack.
Now ```pytest.mark.skipif``` checks for CRISPY_TEMPLATE_PACK setting before test execution. It works for separate test functions and for whole classes as well.
E.g. test class decorated with ```@only_uni_form``` will run only if tests were run with ```CRISPY_TEMPLATE_PACK='uni_form'``` setting otherwise whole class will be skipped to run.
[Here](https://pytest.org/latest/skipping.html#skipping) is doc for test skipping.
I've transformed conditions from https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/tests/runtests.py to marks required test classes. Also base classes were refactored to eliminate repeated tests executions (#465).
> Add marks to skip, fix repeated tests execution. #465

- crispy_forms/tests/conftest.py
- crispy_forms/tests/test_tags.py
Also basic fixture for template-related settings setup added. It has same functionality like [CrispyTestCase](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/tests/base.py#L19)
Main changes are:
* asserts converted from TestCase's to standard python
* test classes are removed
* current_template_pack is replaced with settings.CRISPY_TEMPLATE_PACK
* the rest of the code is just indented left
> Сonvert test_tags.py module to py.test style

- crispy_forms/templatetags/crispy_forms_utils.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
Now, when Django < 1.4 is not supported, this code is not required.
> Remove shims for Django < 1.4

- .editorconfig
- crispy_forms/layout.py
- crispy_forms/templates/bootstrap/field.html
- crispy_forms/templates/bootstrap/layout/alert.html
- crispy_forms/templates/bootstrap/layout/div.html
- crispy_forms/templates/bootstrap/table_inline_formset.html
- crispy_forms/templates/bootstrap3/field.html
- crispy_forms/templates/bootstrap3/layout/alert.html
- crispy_forms/templates/bootstrap3/layout/div.html
- crispy_forms/templates/bootstrap3/layout/formactions.html
- crispy_forms/templates/bootstrap3/layout/inline_field.html
- crispy_forms/templates/bootstrap3/layout/prepended_appended_text.html
- crispy_forms/templates/bootstrap3/table_inline_formset.html
- crispy_forms/templates/uni_form/layout/div.html
- docs/dynamic_layouts.rst
Changes:
- Fix indentation issues
- Add EditorConfig file with rules for HTML, Python, reStructuredText, and Makefile
Besides adding the `.editorconfig` file, these changes only fix indentation.  [See this diff that ignores whitespace changes][whitespace].
I noticed the need for `.editorconfig` when editing the Makefile because my editor wanted to add a final newline which would make unnecessary git noise.
**Disclosure**: I am one of the creators of the EditorConfig project
(replaces #488)
[whitespace]: https://github.com/maraujop/django-crispy-forms/pull/490/files?w=1
> Fix style issues and add EditorConfig file

- crispy_forms/layout.py
- crispy_forms/tests/test_layout_objects.py
Fixes #448, fixes #361
Introduce `get_template_name` method to apply conditional template name resolution. (via @marshalc in [comment here](https://github.com/maraujop/django-crispy-forms/issues/361#issuecomment-128499014))
Apply to both LayoutObject and BaseInput hierarchies.
> Allow LayoutObject & BaseInputs to accept custom template

- .travis.yml
- tox.ini
According to [Django doc](https://docs.djangoproject.com/en/dev/releases/1.9/#python-compatibility), starting from version 1.9 support for Python 3.2 and 3.3 will be dropped.
Also, I've added proper Python 3.2 builds to tox.ini.
> Exclude Python 3.2 and 3.3 from Travis & tox builds

- crispy_forms/templates/bootstrap3/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap3/layout/radioselect.html
Modified layout for checkboxes and radio buttons with Bootstrap 3, so that stacked widgets align with their inline counterparts (as well as other form fields).
Stacked and inline fields do not align:
...but with the changes in this commit, they will:
checkbox_inline = forms.TypedChoiceField(
label=_('Checkbox Inline'),
widget=forms.CheckboxSelectMultiple,
choices=((1, 'Inline 1',), (2, 'Inline 2',), (3, 'Inline 3',), (4, 'Inline 4',),)
)
checkbox_stacked = forms.TypedChoiceField(
label=_('Checkbox Stacked'),
widget=forms.CheckboxSelectMultiple,
choices=((1, 'Stacked 1',), (2, 'Stacked 2',), (3, 'Stacked 3',), (4, 'Stacked 4',),)
)
radio_inline = forms.TypedChoiceField(
label=_('Radio Inline'),
widget=forms.RadioSelect,
choices=((1, 'Inline 1',), (2, 'Inline 2',), (3, 'Inline 3',), (4, …
> Fix for alignment of stacked checkboxes and radio buttons in Bootstrap 3

- MANIFEST.in
Fix for #200 .pyc files for tests were included if the package is built after tests have been run locally. This patch fixes this.
> Don't recursively include .pyc files into tarball

- docs/crispy_tag_forms.rst
The documentation in the AJAX section doesn't specify how to import the `render_crispy_form` function, just adding it in to make it clearer.
> include import statement for AJAX section

- docs/crispy_tag_forms.rst
I had some hangups following the documentation for using render_crispy_form to make AJAX calls to validate forms and replace the HTML on the page since the example code does not include passing the CSRF token back to the form HTML. It was not immediately apparent what the problem was and I think an improved example will save others that are writing their first crispy forms a fair bit of time.
> Updated render_cripsy_form documentation example to show context usage

- requirements.txt
v4 does not support Python 3.2
> Pin coverage to 3.7.1 for Python 3.2

- crispy_forms/helper.py
- crispy_forms/templates/bootstrap/display_form.html
- crispy_forms/templates/bootstrap/uni_form.html
- crispy_forms/templates/bootstrap3/display_form.html
- crispy_forms/templates/bootstrap3/uni_form.html
- crispy_forms/templates/bootstrap4/display_form.html
- crispy_forms/templates/bootstrap4/uni_form.html
- crispy_forms/templates/uni_form/display_form.html
- crispy_forms/templates/uni_form/uni_form.html
- crispy_forms/templatetags/crispy_forms_tags.py
- crispy_forms/tests/forms.py
- crispy_forms/tests/test_form_helper.py
- docs/form_helper.rst
This adds a FormHelper attribute "include_media", which defaults to True and controls whether form media is included with the form. Having this attribute makes it much easier to use crispy forms in scenarios which require special handling of media, such as with javascript loading systems, with django-compressor (in offline compression mode), and when the media might produce duplicate javascript when more than one form is on a page. Without this setting, crispy templates must be overridden, which is somewhat more cumbersome. The pull request includes code changes, documentation changes, and 6 new tests.
> Add include_media FormHelper attribute to make form media inclusion optional

- crispy_forms/bootstrap.py
Issues like #361 or #448 warned about the `Exception Value: not all arguments converted during string formatting` error when overriding the template for `LayoutObject` and `BaseInput`, and were solved with commit 14745fd. I got the same problem while overriding objects from `bootstrap`such as `FieldWithButtons`because they were not using the `TemplateNameMixin.get_template_name` new method they were inheriting from.
> Use TemplateNameMixin to get tmpl in bootstrap

- crispy_forms/helper.py
- crispy_forms/tests/test_utils.py
- crispy_forms/utils.py
Based on issue 538
Fields not included in the explicit layout now render in the order they are provided in `Form.Meta.fields` as one might expect.
This was achieved by replacing methods on sets of fields by corresponding methods on lists, to preserve order. These methods were implemented as two simple helper function. There is a matching (and passing) unit test.
> Fields not included in the explicit layout now render in the order they are provided

- MANIFEST.in
Otherwise tests would fail for people who use the pypi tarball.
> Include test templates in source tarball.

- crispy_forms/bootstrap.py
- crispy_forms/templates/bootstrap3/layout/prepended_appended_text.html
Very much taking its lead from the implementation of `Field` to put back the functionality in the subclass.
`PrependedAppendedText.__init__()` calls `super` so doesn't need this functionality putting back, but `render()` doesn't call `super` and the template doesn't extend from the `Field` template.
> Support wrapper_class in PrependedAppendedText

- crispy_forms/templates/bootstrap4/field.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple_inline.html
- crispy_forms/templates/bootstrap4/layout/field_with_buttons.html
- crispy_forms/templates/bootstrap4/layout/prepended_appended_text.html
- crispy_forms/templates/bootstrap4/layout/radioselect_inline.html
- crispy_forms/templates/bootstrap4/layout/uneditable_input.html
- crispy_forms/templates/bootstrap4/table_inline_formset.html
From the Bootstrap4 migration guide:
- Rename .control-label to .form-control-label
I updated the bootstrap4 templates as required, please merge.
Thanks
Gert
> Bootstrap4: control-label -> form-control-label

- crispy_forms/templates/bootstrap/layout/buttonholder.html
This PR will fix a bug using Django 1.9. The template is missing.
> Add missing template for bootstrap

- crispy_forms/templatetags/crispy_forms_tags.py
- crispy_forms/tests/templates/custom_form_template_with_context.html
- crispy_forms/tests/test_form_helper.py
First of all, the pleasantries because this is a first PR: `django-crispy-forms` is certified awesome (flattery gets you everywhere). :+1: 
This PR adds passing of the origin context through to the context used when rendering forms/fields/etc., such that they can be customised via templates (if desired).  Any context that comes from the helper takes precedence over that which is implicitly carried from templates.
Just to make sure it was actually working I added a test within `test_layout.py`, although I didn't feel like this was the best place to put, there was no-one else that fit exactly either.  If there any issues or concerns, or if additional requests are required, I'd be happy to help out.
Cheers!
Closes #436
> Pass node context through to template via crispy tag

- README.rst
- docs/_templates/sidebarintro.html
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- crispy_forms/bootstrap.py
Closes https://github.com/django-crispy-forms/django-crispy-forms/issues/526
> Fix missing _active_originaly_included #526.

- crispy_forms/templates/bootstrap/field.html
- crispy_forms/templates/bootstrap3/field.html
- crispy_forms/templates/bootstrap4/field.html
Background:
HTML5 does not allow <p> elements inside of <label> elements:
error: Element “p” not allowed as child of element “label” in this context. (Suppressing further errors from this subtree.)
Per https://about.validator.nu/
Closes #632
> Move help and error markup out of <label> element.

- .travis.yml
- crispy_forms/helper.py
- crispy_forms/templates/bootstrap4/field.html
- crispy_forms/templates/bootstrap4/inputs.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple_inline.html
- crispy_forms/templates/bootstrap4/layout/field_with_buttons.html
- crispy_forms/templates/bootstrap4/layout/formactions.html
- crispy_forms/templates/bootstrap4/layout/inline_field.html
- crispy_forms/templates/bootstrap4/layout/prepended_appended_text.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
- crispy_forms/templates/bootstrap4/layout/radioselect_inline.html
- crispy_forms/templates/bootstrap4/layout/uneditable_input.html
- crispy_forms/tests/test_form_helper.py
- docs/install.rst
- Revert "Only add 'row' to 'form-group' if grid layout"
This reverts commit [4bee0fd](https://github.com/maraujop/django-crispy-forms/commit/4bee0fda29dc6a98162856e446a5871aebc5cfb8).
Closes https://github.com/maraujop/django-crispy-forms/issues/613
- Drop `control` CSS group since it was deprecated. (We can also drop it everywhere it is used in the Bootstrap 3 templates, but people might be relying on it for custom CSS themselves)
> Bootstrap 4 improvements

- crispy_forms/templates/bootstrap4/layout/field_errors.html
- crispy_forms/templates/bootstrap4/layout/field_errors_block.html
- crispy_forms/tests/test_form_helper.py
Bootstrap 4 uses form-control-feedback instead of help-block.
> Error message class for Bootstrap 4

- crispy_forms/tests/test_form_helper.py
Rename tests for bootstrap4 because they clash with tests for bootstrap3.
Fix asserts so they actually assert that string presents in the html.
> Fix form helper tests

- crispy_forms/tests/test_utils.py
- crispy_forms/utils.py
Django 1.9 introduced a useful feature where fields can [define custom `BoundField` behavior](https://docs.djangoproject.com/en/1.10/ref/forms/api/#customizing-boundfield). This PR updates the `render_field` utility method to obtain the bound field from [the form's `__getitem__` method](https://github.com/django/django/blob/1.10/django/forms/forms.py#L141-L155), instead of manually constructing a plain `BoundField` instance for the field.
I wrote a test in `test_utils.py`. I verified that it failed before updating the bound field behavior, and passed afterwards.
> Use get_bound_field for fields defining a custom BoundField

- crispy_forms/helper.py
- crispy_forms/templates/bootstrap3/field.html
- crispy_forms/templates/bootstrap4/field.html
- crispy_forms/templatetags/crispy_forms_tags.py
- crispy_forms/tests/test_form_helper.py
For checkbox input label is displayed after the input
so the input have to be aligned with the rest of the form
using col-<device>-offset-<size> class. But sometimes form may have
different sizes on different devices so we have to build offsets
for each pair of device and size.
I'm not sure about removing label_size and bootstrap_device_type attrs but right now they are only used in the case of bootstrap checkbox.
> Support several bootstrap sizes in label_class for checkbox input

- crispy_forms/bootstrap.py
Currently the bootstrap StrictButton ignores any overiding template you set in the helper.
Making it use get_template_name from Layout.TemplateNameMixin will fix this.
> Make Bootstrap StrictButton use get_template_name() from TemplateNameMixin

- docs/form_helper.rst
I believe it is good to provide in example import for own library. It's easier in this case to use an example, because there is no need to look for additional paths Import.
> Add info about FormHelper import

- crispy_forms/templatetags/crispy_forms_field.py
- crispy_forms/templatetags/crispy_forms_filters.py
- crispy_forms/templatetags/crispy_forms_tags.py
- crispy_forms/tests/forms.py
- crispy_forms/tests/test_layout.py
- crispy_forms/utils.py
`MIN_NUM_FORM_COUNT` was implemented in Django 1.7.
The check was useful when the project supported lower versions of Django.
----
Since the project does not support Django versions lower than 1.8, there is no need to check whether they are greater than 1.6 or 1.7.
> Remove useless checks in code

- crispy_forms/helper.py
That fixes warning: RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.
That also mean this code will continue to work on Django 2.0
> Fixed RemovedInDjango20Warning for django.core.urlresolvers

- docs/install.rst
Docs point to 1.5 version of Django. This link does not work, since 1.5 version is not supported anymore
> Update docs link to cached template loader

- crispy_forms/bootstrap.py
- crispy_forms/helper.py
- crispy_forms/layout.py
- crispy_forms/layout_slice.py
- crispy_forms/templatetags/crispy_forms_field.py
- crispy_forms/templatetags/crispy_forms_filters.py
- crispy_forms/templatetags/crispy_forms_tags.py
- crispy_forms/templatetags/crispy_forms_utils.py
- crispy_forms/tests/conftest.py
- crispy_forms/tests/test_dynamic_api.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
- crispy_forms/tests/test_settings.py
- crispy_forms/tests/test_tags.py
- crispy_forms/tests/test_utils.py
- crispy_forms/tests/urls.py
- crispy_forms/utils.py
- setup.cfg
I have sorted imports using `isort`. The rule which I used is included also.
> Sort import statements. Remove some unused ones

- .travis.yml
- crispy_forms/tests/test_layout.py
- tox.ini
Ref #683.
This doesn't solve the issue but should allow the tests to pass.
> Skip l10n tests for Django 1.11

- crispy_forms/templates/bootstrap3/layout/multifield.html
- crispy_forms/templates/bootstrap3/multifield.html
Closes #478 
Hi!
We're using a MultiField with django-crispy-forms v.1.5.2 and were getting error **bootstrap3/multifield.html cannot be found** similar to #428 or #515 (which are more specific than #478 which also encompasses ButtonHolder).
We discovered that _bootstrap3/multifield.html_ was missing, and that there was a b_ootstrap3/layout/multifield.html_ file present. 
But that _bootstrap3/layout/multifield.html_, compared to uni_form's, was similar to https://github.com/maraujop/django-crispy-forms/blob/1.5.2/crispy_forms/templates/uni_form/multifield.html and really intended for the field only. 
So we moved it to _bootstrap3/multifield.html_ and gave it bootstrap markup.
We also created a _bootstrap3/layout/multifield.html_ based on uni-form's …
> Fixes #478 bug about missing multifield template in bootstrap3

- crispy_forms/helper.py
- crispy_forms/templatetags/crispy_forms_tags.py
We should still respect the configuration of the Helper object when rendering Meta fields, including `render_unmentioned_fields`, `render_hidden_fields`, and `render_required_fields`.
> Respect helper configuration when rendering Meta fields

- crispy_forms/templatetags/crispy_forms_field.py
I'm reopening #356 as `form-control` CSS class is added to file inputs if they are not clearable
In the previous pull-request, tests seem to have fail due to another issue...
> Check for FileInput instead of ClearableFileInput

- crispy_forms/helper.py
- crispy_forms/templates/bootstrap4/field.html
- crispy_forms/templates/bootstrap4/inputs.html
- crispy_forms/templates/bootstrap4/layout/prepended_appended_text.html
So I should've done what @yunti originally recommended on #613 
This tidies this up horizontal forms a lot:
```
-        Field('text_input', css_class='form-control-lg', wrapper_class='row'),
-        Field('textarea', rows="3", css_class='form-control-lg', wrapper_class='row'),
-        Field('radio_buttons', wrapper_class='row'),
-        Field('checkboxes', style="background: #FAFAFA", wrapper_class='row'),
-        AppendedText('appended_text', '.00', wrapper_class='row'),
-        AppendedText('appended_text2', '.00', css_class='form-control-lg', wrapper_class='row'),
+        Field('text_input', css_class='form-control-lg'),
+        Field('textarea', rows="3", css_class='form-control-lg'),
+        Field('radio_buttons'),
+        Field('checkboxes', style="background: #FAFAFA"),
+ …
```
> Form level group wrapper classes makes horizontal forms DRYer

- crispy_forms/bootstrap.py
The `extra_context` argument is ignored in `PrependedAppendedText.render()`. This fix makes sure both dictionaries are merged, but don't affect each other.
> Fix passing `extra_context` argument to PrependedAppendedText.render()

- docs/layouts.rst
`AccordionGroup` must exist within `Accordion` layout object.
> Fix documentation for `Accordion` layout object

- crispy_forms/layout.py
The code check in `Field.__init__()` checks whether `self.attrs` is already set. However, this assumes that `hasattr()` resolves an object-level variable, assigned by a super `__init__()`. Potentially `attrs` can be defined as class variable, causing it to be shared between multiple `Field` instances.
While this likely didn't happen yet, I'd rather be on the safe side here. (in fact I did experience some shared state for the `help_text` before)
> Avoid risk for editing shared state via `self.attrs`.

- crispy_forms/templatetags/crispy_forms_field.py
Similar to MultiWidget that has an attribute `widgets` that wraps actual widgets, [RelatedFieldWidgetWrapper](https://github.com/django/django/blob/master/django/contrib/admin/widgets.py#L250) has an attribute `widget` that is the actual widget.
> Added support for RelatedFieldWidgetWrapper to crispy_field tag rendering.

- .travis.yml
- README.rst
- tox.ini
Both are passed their end-of-life date; see
- https://www.python.org/dev/peps/pep-0392/
- https://www.djangoproject.com/weblog/2017/apr/04/security-releases/
> Removed support for Python 3.2 and Django 1.9

- crispy_forms/templatetags/crispy_forms_tags.py
Maybe I missed something but I would like to have access to the form which is currently rendered inside a formset. I.E. to do something like this with an inline formset
`Layout(HTML('<h4>{{ formset_form.instance }}</h4>'), ...)`
Where formset_form is the current form. Is there any reason not to include the form in the context or is there another way apart from doing the loop over the formset in my own template?
> Add current formset form to context

- .travis.yml
- Django 2.0 has been released: https://www.djangoproject.com/weblog/2017/dec/02/django-20-released/
- Django 1.10 reached its EOL: https://www.djangoproject.com/weblog/2017/dec/02/django-20-released/
- Python 3.3 reached its EOL: https://www.python.org/dev/peps/pep-0398/#x-end-of-life
> Update test matrix

- tox.ini
Not sure if it actually runs the tests for it twice, but:
```tox -l | sort -n | uniq -c
1 py27-django110
1 py27-django111
1 py27-django18
1 py33-django18
1 py34-django110
1 py34-django111
1 py34-django18
1 py35-django110
2 py35-django111
1 py35-django18
1 py35-djangolatest
1 py36-django111
1 py36-djangolatest```
> We have a tox env twice

- crispy_forms/templates/bootstrap4/table_inline_formset.html
Bootstrap 3 used a class="hidden" attribute to hide content:
https://getbootstrap.com/docs/3.3/css/#helper-classes-show-hide
Bootstrap 4 uses class="d-none":
https://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements
I've updated the bootstrap 4 templates to reflect this.
> Bootstrap 4 does not use hidden any more

- crispy_forms/templates/bootstrap4/layout/field_with_buttons.html
- crispy_forms/tests/test_layout_objects.py
Fix the class used in the `FieldWithButtons` layout
Bootstrap 4 now uses `input-group-append`
> Fix FieldWithButtons layout

- crispy_forms/templates/bootstrap4/accordion-group.html
- crispy_forms/templates/bootstrap4/accordion.html
- crispy_forms/tests/test_layout_objects.py
This fixes `Bootstrap 4` HTML for accordion and accordion group in `django-crispy-forms`
> Update Bootstrap 4 accordion and accordion group

- Makefile
- crispy_forms/templates/bootstrap4/field.html
- crispy_forms/templates/bootstrap4/layout/field_file.html
- crispy_forms/templatetags/crispy_forms_field.py
The Issue #734 suggested to add custom file input for Bootstrap 4.
A new layout template called `file_input.html` was created which holds the HTML of the Bootstrap4 [custom file input](https://getbootstrap.com/docs/4.0/components/input-group/#custom-file-input)
A distinction was included in `field.html` which checks if the field to render is a file input field using `is_file`.
The classes `form-control` and `is-invalid` are added to the field input in order to show form errors for the field.
> Custom file input field for Bootstrap 4

- crispy_forms/templatetags/crispy_forms_field.py
- crispy_forms/tests/test_tags.py
@carltongibson I've recreated pull request, this time with a regression test. The bug is triggered when `{% crispy_field %}` is inside another Django block tag, so existing test wasn't triggering it.
> Fixed incompatiblity issue with Django 2.0.

- setup.cfg
See http://doc.pytest.org/en/latest/changelog.html
From pytest 4.0. Will stop working for pytest 4.1
> Ignore pytest.RemovedInPytest4Warning

- docs/_templates/sidebarintro.html
- docs/_themes/kr/layout.html
- docs/_themes/kr_small/layout.html
Closes https://github.com/django-crispy-forms/django-crispy-forms/issues/850
I might be missing some.
The two in the reported issue are fixed.
> Fix non-HTTPS resources

- crispy_forms/templates/bootstrap4/field.html
- crispy_forms/templates/bootstrap4/layout/field_with_buttons.html
- crispy_forms/templates/bootstrap4/layout/prepended_appended_text.html
- crispy_forms/templates/bootstrap4/layout/uneditable_input.html
Bootstrap4 col-form-label class should be included only on horizontal forms. #810
> fixes .col-form-label added for vertical forms #810

- crispy_forms/templates/bootstrap4/layout/prepended_appended_text.html
The error message have to be in the input-group while the help text have to be outside, splitting the content of help_text_and_errors to do so.
Note that the left part being not rounded is a bug from BS4 itself as we can see in https://getbootstrap.com/docs/4.0/components/forms/#server-side
> Making the error message visible for input-group-prepend in BS4

- crispy_forms/templates/bootstrap/layout/radioselect.html
- crispy_forms/templates/bootstrap3/layout/radioselect.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
https://github.com/django-crispy-forms/django-crispy-forms/pull/758 introduced wrong ID calculations for checkboxes and radio selects, resulting in `id_id_htmlname_0_index` instead of the expected `id_htmlname_index` of stock Django.
https://github.com/django-crispy-forms/django-crispy-forms/pull/783 has fixed this for checkboxselectmultiple already.
This PR fixes it for radio selects.
> Fix IDs of radio selects

- crispy_forms/helper.py
- crispy_forms/templates/bootstrap4/field.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
- crispy_forms/templatetags/crispy_forms_field.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
- docs/form_helper.rst
This PR adds the validation 'is-invalid' classes to the remaining field types (checkbox, checkbox multiple and radios).  Fixes #865 
With this work I was changing the same lines as PR #892 so I've included those fixes there, along with the updated tests required for this change. 
For the inline radios and checkbox the format doesn't look right when the validation fails and the error message is displayed. A bit of research seems to indicate this is a known bug in bootstrap 4 and has been fixed for bootstrap 5. [Bootstrap issue](https://github.com/twbs/bootstrap/issues/25540)
Tests have been updated and are passing and below is the image of the current output. 
Edit: Fixed typo on first line.
> Bootstrap4 radio & checkbox

- tox.ini
Current tests are being run against v2 and latest. Tests against latest are ignored and so failing tests are easy to miss.
Updated tox.ini to explicitly test against v.3 of Django and to make tests for v.3 fail loudly.
p.s. Tests against latest are failing with an import error. They were previously passing.
> Explicitly test against Django v3.

- crispy_forms/tests/test_form_helper.py
The test noted below was not running, I'm assuming this is due to
there being another test in the test_form_helper.py file with the same name.
Therefore I updated test name to allow test to run
Test not currently running:
@only_bootstrap3
def test_error_and_help_inline
> rename test to improve coverage

- crispy_forms/templates/bootstrap3/layout/help_text.html
In current Django versions, the `help_text` of a password reset form contains a `<ul>` with password validation rules. These cannot be rendered within a `<p>`, so render it using a `<div>`.
> bootstrap3 help_text.html: div instead of p

- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple_inline.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
- crispy_forms/templates/bootstrap4/layout/radioselect_inline.html
This PR fixes IDs for checkbox labels. 
Some discussion on this at #816. I think what I spotted was a different issue to the end of that discussion. 816 was referring to `id_id`. The code I spotted that was wrong was outputting `id__#` (double underscore), my fix now outputs `id_name_#`
**Old:**
**New:**
@carltongibson do you think it's worth adding a test to check for the format of ids? (not sure how hard this will be, but am willing to give it a go!
EDIT: 
Oops - forgot about the tests so it looks like there is already something in place. Will try and look at tomorrow.
> Fix ID on labels

- crispy_forms/templates/bootstrap4/layout/field_file.html
Add errors to file field template. This way, the errors are displayed as in the rest of the crispy fields.
> Add errors to file field.

- crispy_forms/helper.py
Earlier there was a "You can see it to `POST` or `GET`"
That should be "You can set it to `POST` or `GET`"
>  grammer correction

- crispy_forms/tests/test_layout_objects.py
Add tests to check that when labels are set to `False` that no label is printed.
Currently the bootstrap templates are still printing the label for boolean fields. I have therefore removed that field from the test.
> Test labels do not print when label = False

- crispy_forms/layout.py
- crispy_forms/tests/test_layout.py
Hello @carltongibson , I have replaced the  row with form-row in class Row. This is for the issue #857 . 
The form-row is the variation of bootstrap's standard grid row that overrides the default column gutters for tighter and more compact layouts .
> Adjusted Row CSS class depending on template pack.

- docs/_templates/sidebarintro.html
- docs/form_helper.rst
- docs/index.rst
- docs/install.rst
1. Changed links in documentation to point at current django-crispy-form repo (sidebar & index files)
2. Moved new BS4 control (use_custom_control) to a new BS4 helper section (form_helper)
> Documentation | Links update & layout change

- crispy_forms/templates/bootstrap4/layout/formactions.html
Before
After
Errors in text_input_a text_input_b and text_input_c are adressed by #915 and #916
> BS4 Corrected form actions margin.

- crispy_forms/layout.py
- crispy_forms/templates/bootstrap/layout/column.html
- crispy_forms/templates/bootstrap3/layout/column.html
- crispy_forms/templates/bootstrap4/layout/column.html
- crispy_forms/templates/uni_form/layout/column.html
- crispy_forms/tests/test_layout.py
All the css class are out of layout.py in independant html template
=> Add support of column out-of-the-box for BS4
Bugfix
=> remove the usage of css class `formColumn` in BS3 & BS4
Before
After
> Reworking layout.Column so it uses only template + bugfix

- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
This is the proposed fix for #929. It removes `is-valid` and `is-invalid` styling for bound forms in checkboxselectmultiple and radioselect.
> Remove is-valid styling from checkboxselectmultiple and radioselect

- docs/install.rst
- docs/template_packs.rst
I've started to review the docs. I thought it best to do one page at a time to make a review more manageable. Here is my proposal for updated install instructions. In short it removes much of the old notes about migration from 'django-uni-form'. 
It's probably worth some discussion on the other areas before I go too far (I think a structural change to the other pages is probably the next step)
key changes :
removed reference to 'easy install'
removed reference to 'django-uni-form'
removed install instructions for static (we don't provide this)
improved notes on pack (create your own)
> update install documentation

- .travis.yml
- tox.ini
- Python 3.8 is now official
- Django 2.x is not officially compatible with Python 3.8
- Cleanup indent in tox.ini
> Cleanup CI configuration

- crispy_forms/helper.py
- crispy_forms/tests/forms.py
- crispy_forms/tests/test_form_helper.py
Fixes #951 
Follows https://github.com/django-crispy-forms/django-crispy-forms/pull/539#issuecomment-307984618
The first loop is a superset of the second loop.
Let's combine the loops and use the order in Meta, followed by the order in form.
More info: [https://stackoverflow.com/questions/59101176/how-do-i-specify-the-order-of-fields-in-a-form-django-crispy-forms/59120457#59120457](https://stackoverflow.com/a/59120457/8601760)
> Render fields not included in the explicit layout in the order they are provided

- .travis.yml
- CHANGELOG.md
- CONTRIBUTORS.txt
- crispy_forms/bootstrap.py
- crispy_forms/compatibility.py
- crispy_forms/helper.py
- crispy_forms/layout.py
- crispy_forms/layout_slice.py
- crispy_forms/templatetags/crispy_forms_field.py
- crispy_forms/templatetags/crispy_forms_tags.py
- crispy_forms/templatetags/crispy_forms_utils.py
- crispy_forms/tests/test_dynamic_api.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/utils.py
This PR removes support for python 2. 
1) Update tox.ini and travis.yml to stop testing for python 2
2) removal of python 2 in compatibility.py, and put python 3 commands into individual files
3) removal of izip in crispy_forms_field
4) added to change log (I've not change the readme file, so this still refers to python 2 (v1.8 supports python 2). We will need to change this at some point.
Looking forward to the review and feedback.
> Remove Python 2 support

- crispy_forms/templatetags/crispy_forms_field.py
Bootstrap 4 uses the "form-control-file" class for file input fields but the "form-control" class was incorrectly being applied to file input fields leaving a field border that is not present in Bootstrap 4 Documentation.
This will append to the class to correct the class string.
> Ref #926 Fix class on File upload input field.

- crispy_forms/templatetags/crispy_forms_utils.py
Fix this warning seen on Django 3.0:
```
.../site-packages/crispy_forms/templatetags/crispy_forms_utils.py:25: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
html = re.sub(r'>\s{3,}<', '> <', force_text(value))
```
> Fix Django 3.0 deprecation warning

- .github/workflows/flake8.yml
- crispy_forms/compatibility.py
- crispy_forms/templatetags/crispy_forms_tags.py
- crispy_forms/tests/test_form_helper.py
- setup.cfg
Here is the first small step towards exploring github actions. 
This PR enables flake8 only. To get the 'test' to pass I have had to amend a couple of test names (good spot flake8!?), and I've added some exceptions. 
I've had to take an opinion on the settings for flake8. I've copied GitHub's recommendations with the exception of line length. 
This leaves c.50 'errors' on the current code base. We will need to consider how to approach these.
> Add GitHub actions for Flake8

- CHANGELOG.md
- crispy_forms/templates/bootstrap4/layout/column.html
- crispy_forms/tests/test_layout.py
This PR is to fix #963 
Improved default CSS to `col-md` for bootstrap 4 so columns stack on smaller screens by default. If additional css classes are added the default is removed if it includes a `col` class. New tests are provided for this functionality. 
My main question is this explicit enough, is this too clever and gives a surprising / unexpected result?
> Improve CSS for column layout object

- CHANGELOG.md
- crispy_forms/helper.py
- crispy_forms/templatetags/crispy_forms_utils.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
- crispy_forms/tests/test_utils.py
- tox.ini
To remove compatibility for Django version 1.
The one bit which needed further research as it's not documented in the code is `_get_new_csrf_string`. Django docs show 'string' in [django version 2.2](https://docs.djangoproject.com/en/2.2/_modules/django/middleware/csrf/) and 'key' in [django version 1](https://docs.djangoproject.com/en/1.8/_modules/django/middleware/csrf/). I've therefore removed the option to try for 'key'.
> Drop Django V1 support

- crispy_forms/templatetags/crispy_forms_filters.py
- crispy_forms/tests/test_tags.py
- crispy_forms/tests/test_utils.py
This [commit](https://github.com/django/django/commit/129583a0d3cf69b08d058cd751d777588801b7ad#diff-7a3347e3650b9f77b33b71f753d73751) in Django master removed some backwards compatibility support. 
Some of the django-crispy-form tests were relying on this and therefore the change to Django master broke the tests.
I've updated the import locations to allow the tests to work against django master.  
EDIT:
I (wrongly) assumed this was just needed a change to the import locations in the test files, so change to WIP. 
EDIT 2:
Ok, looks like this works now.
> Update imports to support django latest

- .github/workflows/flake8.yml
- crispy_forms/helper.py
- crispy_forms/templatetags/crispy_forms_field.py
- crispy_forms/tests/test_form_helper.py
- crispy_forms/tests/test_layout.py
- crispy_forms/tests/test_layout_objects.py
- crispy_forms/tests/test_utils.py
- crispy_forms/utils.py
We started to use github actions at the end of last year. The first step is to get flake8 working and currently it is configured to run on push so that it doesn't give errors on pull requests. 
This pull requests finalises flake8 compatibility and therefore I also propose we move to running flake8 for all pull requests. Yes we have #noqa flags in a few places but I think there is value in adding flake8 on `pull_request` now. 
I'll look to raise the current noqa flags on an issue so we can tackle those separately. Some of these (e.g. C901 below) would imply re-write of the main render function and therefore warrants deeper thought.
> Flake8 on pull request

- .github/workflows/ci-testing-django-master.yml
- .github/workflows/ci-testing.yml
This pull request adds C/I testing using GitHub actions. This gives the same test scenarios as currently configured on Travis CI. This is another step in transitioning to GitHub actions. 
I've added two for files, one to test against published releases of Django and another for testing against Django latest / master branch. For the published releases version I've also added caching so downloads don't have to keep taking place each time the tests are run.
Currently tests are failing against Django master as we need #947 to be merged. 
For completeness (I don't think it's a biggie for this project) one potential downsides of GitHub over Travis is testing against new versions of Python. We had tests running against 3.8dev for a long time with Travis, and GitHub took a while to add support …
> GitHub Actions C/I testing

- docs/form_helper.rst
Issue #886 raised that the docs could be more clear on the purpose of the render_hidden_fields feature. I've added a few words to try and help in future. 
Closes #886
> Improve render_hidden_fields docs fixes #886

- crispy_forms/helper.py
- crispy_forms/tests/test_form_helper.py
When using horizontal form like in crispy test project, allow to use col-4 is not only col-sm-4:
```
class HorizontalMessageForm(forms.Form):
(...)
helper = FormHelper()
(...)
helper.form_class = 'form-horizontal'
helper.label_class = 'col-4'
helper.field_class = 'col-8'
```
Before:
Fixe:
> Improve pattern to encompass BS4 css col class such as col-4

- crispy_forms/tests/urls.py
url() is deprecated in Django4.0
> Changed urlpatterns to use path

- README.rst
@carltongibson @bryan-brancotte 
Django 3.1 is coming 🎉 
However, `crispy-forms` version 1.9+ is required to work with Django 3.1. To try and communicate this I've added a note to the readme. Is this enough?
Appreciate thoughts.
> Django 3.1 requires version 1.9 or higher

- crispy_forms/templatetags/crispy_forms_tags.py
New `flake8` version starts to raise an error for not having imports at the top of the file (E402)
Tests fail if register variable is not created before importing filters
> Suppressed flake8 error

- docs/layouts.rst
Breaks syntax highlighting, see https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#bootstrap-layout-objects (scroll to the `Alert` section).
> Avoid invalid Python in documentation

- crispy_forms/bootstrap.py
- crispy_forms/templates/bootstrap4/accordion-group.html
- crispy_forms/templates/bootstrap4/accordion.html
- crispy_forms/tests/test_layout_objects.py
The Accordion unique ID is generated on the constructor of
Accordion and passed to its AccordionGroup.
> Fix `data-parent` in the AccordionGroup to refer to the Accordion id

- .github/workflows/flake8.yml
Flake8 github action is currently failing silently. 
If I remember correctly this was so we could get it working and then go and fix and errors. Now that we have it working let's make it fail loudly. 
This SHOULD fail as the new version of flake8 raises an error see #1052.
Once that is merged, we can re-run the checks on this PR and it should then pass.
> Make flake8 fail loudly

- .github/workflows/ci-testing-django-master.yml
Django master branch no longer supports Python 3.6 and 3.7.
> Updated Python Version Matrix for Django Master

- .github/workflows/ci-testing-django-master.yml
- tox.ini
While we're here we should replace `whitelist` with `allowlist` in tox.
I'll try and find time to make the change to the crispy-forms org.
> Renamed Django's dev branch to main

- crispy_forms/compatibility.py
- crispy_forms/templatetags/crispy_forms_filters.py
- crispy_forms/templatetags/crispy_forms_tags.py
- crispy_forms/utils.py
lru_cache is available in functools in all supported versions of Python. Therefore can remove compatibility.py
> Used lru_cache from standard library

- crispy_forms/tests/results/utils_test.html
- crispy_forms/tests/test_utils.py
- crispy_forms/tests/utils.py
This allows the expected html to be stored in an HTML file. Tests can then assert the layout of the whole form.
I've been using this method with the bootstrap5 template pack and have been enjoying working in this way. 
I'd like to introduce this here as I think it is helpful generally, I find that tests are more readable as you can see all of the output. It's also then easier to have a discussion about if there is an issue as you can point to the line in the html code that is in question. 
More specifically I think it will be helpful to prove the optgroup filter and upcoming changes are ok as we'll clearly be able to see the changes that happen (hopefully none :crossed_fingers: ) which I think could be missed with the current approach.
> Added html parsing tools for testing

- crispy_forms/templates/bootstrap4/layout/field_file.html
- crispy_forms/tests/forms.py
- crispy_forms/tests/test_layout.py
I've explained the issue a bit more in #1129 .
The main change is that the template now uses `widget.data.attrs` and that `widget.data.attrs.class` is explicitly rendered when it's there. Please let me know if you need more/different test coverage or different naming.
> Fixed #1129: render all widget attributes for file fields in bootsrap4

- crispy_forms/tests/results/bootstrap4/file_field/clearable_file_field.html
- crispy_forms/tests/results/bootstrap4/file_field/clearable_file_field_custom_class.html
- crispy_forms/tests/results/bootstrap4/file_field/clearable_file_field_custom_control.html
- crispy_forms/tests/results/bootstrap4/file_field/file_field.html
- crispy_forms/tests/results/bootstrap4/file_field/file_field_custom_class.html
- crispy_forms/tests/results/bootstrap4/file_field/file_field_custom_control.html
- crispy_forms/tests/test_layout.py
Previous tests were failing due to `dict` being unordered on Python 3.5.
Following 7588f3df712be0ee3ae495979a97be059441a9ec the tests failed. See [logs](https://github.com/django-crispy-forms/django-crispy-forms/actions/runs/656748374). I've re-written the tests using the new parsing tool. I'm starting to really enjoy writing crispy-form tests in this way.
> Fixed file field tests

- CHANGELOG.md
- crispy_forms/bootstrap.py
- crispy_forms/templates/bootstrap4/layout/prepended_appended_text.html
- crispy_forms/tests/test_layout_objects.py
- docs/layouts.rst
@cpina this is still WIP, but thought it worth sharing more publicly my progress with this. Notes:
- I think your solution for the button groups by adding an extra argument of `input_size` is spot on. I think we need this for the append inputs as well
- This is due to bs3 and 4 having different behavior. On bs3 we want the spans and input to have a class, for bs4 we want the wrapping div to have the class (and only the wrapping div). 
- Adding this additional argument allows us to manage this flexibility -- I think we'll also need this for the bs5 pack, so will make things easier there.
- `Field_with_buttons` I've not really looked at. Tempted to chop it from this PR and get the rest of it merged.
> Fixed input group size in Bootstrap 4

- crispy_forms/templatetags/crispy_forms_filters.py
- crispy_forms/tests/forms.py
- crispy_forms/tests/test_utils.py
Supersedes #1121 
This is slimmed down to just the new filter and tests. 
Needed to add `values = field.field.widget.format_value(field.value())` compared to the previous version to correctly format the values. You'd see the test where an integer is passed in would fail without this.
EDIT: 
I'm assuming this is easier to review without template changes. That can come as follow-up PRs. Do let me know if you disagree!
David
> Added optgroups filter and tests

- crispy_forms/templates/bootstrap/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap/layout/radioselect.html
- crispy_forms/templates/bootstrap3/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap3/layout/radioselect.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
- crispy_forms/tests/test_layout_objects.py
When we move to the new optgroups filter the ids for the inputs will be start from zero rather than one. I'm making this change now so we have a smaller diff later on. (or atleast that's the intention!)
I'm wondering if this is backwards incompattible change? Any comments?
> Zero index checkbox and radio in bootstrap templates

- CHANGELOG.md
- crispy_forms/templates/bootstrap4/layout/attrs.html
- crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html
- crispy_forms/templates/bootstrap4/layout/radioselect.html
- crispy_forms/tests/forms.py
- crispy_forms/tests/results/bootstrap4/test_layout/test_use_custom_control_is_used_in_radio_false.html
- crispy_forms/tests/results/bootstrap4/test_layout/test_use_custom_control_is_used_in_radio_true.html
- crispy_forms/tests/results/bootstrap4/test_layout_objects/test_grouped_checkboxes.html
- crispy_forms/tests/results/bootstrap4/test_layout_objects/test_grouped_radios.html
- crispy_forms/tests/test_layout_objects.py
So here we are 🎉 This fixes the long standing bug with grouped choices sets.
Fixes #690 and Follows #1119 and #813
I'll leave this here for comments, and look at pulling some of the related changes into separate PRs. There's also a few things which I want to take a closer look at.
> Fixed Grouped Choices for Radios and Checkboxes

- crispy_forms/layout.py
We can avoid a `len()` call, a lookup and a type comparison for each field by moving this line outside of the loop. 
Not sure about the name `str_class` as the variable name, but I'm I guess it'll do.
> Improved performance of get_layout_objects().

- crispy_forms/layout.py
- crispy_forms/tests/results/bootstrap3/test_layout/test_multiple_fields.html
- crispy_forms/tests/results/bootstrap4/test_layout/test_multiple_fields.html
- crispy_forms/tests/test_layout.py
so....
The `Field` docstring says "It contains one field name" yet the `wrap_together` docs say
```
We could do::
form.helper[0:3].wrap_together(Field, css_class="hello")
We would end up having this layout::
Layout(
Field(
'field_1',
'field_2',
'field_3',
css_class='hello'
)
)
```
True enough you can pass multiple fields to `Field` and have the attributes get applied to each of them.
I'm not sure which behaviour is correct.
I guess the best answer is document the current behaviour and give a note about providing something like `id` if you are doing to do this....
> Multiple Fields

- README.rst
- docs/install.rst
Hi,
I would like to add a link to [crispy-bulma](https://github.com/ckrybus/crispy-bulma) template pack. 
I've been using django-crispy-forms with bootstrap since 2013 and [django-crispy-bulma](https://github.com/python-discord/django-crispy-bulma) since 2019, but unfortunately django-crispy-bulma has been archived a while ago :-(
Since I'm using it in multiple projects in production I've decided to revive it and maintain it over the long term.
It's still a work in progress, but it is almost feature complete and hopefully it will get even better in the next few weeks.
> Link to crispy-bulma template pack

- crispy_forms/bootstrap.py
- crispy_forms/templates/bootstrap3/layout/field_with_buttons.html
- crispy_forms/templates/bootstrap4/layout/field_with_buttons.html
`render_field()` returns a SafeString so let's preserve that in the `context` so the `|safe` filter in the template is not required.
> Removed `|safe` filter from `FieldWithButtons` templates.

- crispy_forms/templates/bootstrap3/accordion-group.html
- crispy_forms/templates/bootstrap3/accordion.html
- crispy_forms/templates/bootstrap3/layout/alert.html
- crispy_forms/templates/bootstrap3/layout/buttonholder.html
- crispy_forms/templates/bootstrap3/layout/column.html
- crispy_forms/templates/bootstrap3/layout/div.html
- crispy_forms/templates/bootstrap3/layout/fieldset.html
- crispy_forms/templates/bootstrap3/layout/formactions.html
- crispy_forms/templates/bootstrap3/layout/modal.html
- crispy_forms/templates/bootstrap3/layout/multifield.html
- crispy_forms/templates/bootstrap3/layout/row.html
- crispy_forms/templates/bootstrap4/accordion-group.html
- crispy_forms/templates/bootstrap4/accordion.html
- crispy_forms/templates/bootstrap4/layout/alert.html
- crispy_forms/templates/bootstrap4/layout/buttonholder.html
- crispy_forms/templates/bootstrap4/layout/column.html
- crispy_forms/templates/bootstrap4/layout/div.html
- crispy_forms/templates/bootstrap4/layout/fieldset.html
- crispy_forms/templates/bootstrap4/layout/formactions.html
- crispy_forms/templates/bootstrap4/layout/modal.html
- crispy_forms/templates/bootstrap4/layout/row.html
The content for these fields is already a `SafeString` therefore the `|safe` filter is not required.
> Removed unrequired `|safe` filters.

- crispy_forms/utils.py
Follow up to 082c8468c7ed3c6302de2201c0cafb71a280c6c3.
> Made `render_field()` return `SafeString` when `field_instance` is `None`.

- CHANGELOG.md
- crispy_forms/bootstrap.py
- crispy_forms/helper.py
- crispy_forms/layout.py
- crispy_forms/layout_slice.py
- tests/test_dynamic_api.py
The current implementation returns a list of lists.
Each list has two items:
- A list of locations (int)
- The name of the object/field. (str)
This PR replaces the list with a dataclass to improve the readability of the code and to help when adding type hints.
That is the current type is Union[List[int], str]. Accessing the first item can therefore by either of these types. However, we know the type is specifically List[int]. Using a dataclass allows each component to by typed individually.
> Improved get_layout_objects() to return a list of Pointers. 

- docs/crispy_tag_formsets.rst
There is a small typo in docs/crispy_tag_formsets.rst.
Should read `hypothetical` rather than `hypothetic`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, hypothetic -> hypothetical

- pyproject.toml
The 4.2 classifier is not yet available and is blocking the 2.0a1 release.
> Drop Django 4.2 Classifier.

- docs/install.rst
I came across unusuall problem after installing crispy-forms v2.0. After some googling, i fell on a solution on StackOverFlow and worried why it was not mentioned on the crispy-forms official documentation site.
This is the link to the StackOverFlow solution https://stackoverflow.com/questions/75495403/django-returns-templatedoesnotexist-when-using-crispy-forms
> Updated install docs to list new template packages

- docs/contributing.rst
Seeing "trunk" in contributing.rst is confusing so I removed it. It turns out the instructions are quite old, from 2012, probably when the project was still hosted on code.google.com.
> Replace trunk with main/upstream in contributing.rst

- .github/CODE_OF_CONDUCT.md
Adding a reference to say that we follow Django's code of conduct.
See [docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) and discussion from when this was added to Django itself: https://github.com/django/django/pull/15057
> Enabled GitHub code of conduct.
